# -*- coding: utf-8 -*-
"""BRAIN TUMOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ki-yxTCdx-ePqqarZbkbAKaPIZygjzKJ

### Building a Traditional Machine Learning Model for Image Classification

Now that the images are organized, we can proceed to build a classification model. As requested, this will *not* use deep learning. We will follow these steps:

1.  **Load Images and Assign Labels**: Read all images from the `dataset/YES` and `dataset/NO` folders and assign a numerical label (e.g., 1 for YES, 0 for NO).
2.  **Feature Extraction**: Extract relevant features from each image. We'll use Histogram of Oriented Gradients (HOG) which captures edge and shape information effectively.
3.  **Data Preparation**: Split the extracted features and labels into training and testing sets.
4.  **Model Training**: Train a `RandomForestClassifier` on the training data.
5.  **Model Evaluation**: Assess the model's performance on the test set using metrics like accuracy and a classification report.

#### 1. Load Images and Assign Labels

This cell loads all images from the `dataset/YES` and `dataset/NO` directories, resizes them to a consistent size (128x128 pixels), and assigns appropriate labels.
"""

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

# Define the base directory where organized images are located
image_dir = Path("dataset")

features = []
labels = []
image_size = (128, 128) # Define a consistent image size for feature extraction

print("Loading images and labels...")

# Iterate through 'YES' and 'NO' subdirectories
for label_name in ["NO", "YES"]:
    current_dir = image_dir / label_name
    label = 1 if label_name == "YES" else 0 # 1 for YES (tumor), 0 for NO (no tumor)

    if not current_dir.exists():
        print(f"Warning: Directory '{current_dir}' not found. Skipping.")
        continue

    for img_file in os.listdir(current_dir):
        img_path = current_dir / img_file
        # Check for common image file extensions
        if img_path.is_file() and img_file.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".gif")):
            img = cv2.imread(str(img_path))
            if img is not None:
                # Resize image for consistent feature extraction
                img = cv2.resize(img, image_size)
                features.append(img)
                labels.append(label)

print(f"Loaded {len(features)} images with corresponding labels.")

# Convert lists to numpy arrays
# Note: features here are still raw image data, not extracted HOG features yet
# We convert them to a list for now, as HOG extraction will convert them individually.
# If no images are loaded, ensure features and labels are empty lists, not None.
if not features:
    print("No images were loaded. Please ensure the 'dataset' directory and its 'YES'/'NO' subdirectories exist and contain images.")
    features_array = np.array([])
    labels_array = np.array([])
else:
    features_array = np.array(features)
    labels_array = np.array(labels)

"""#### 2. Feature Extraction (HOG)

This cell extracts Histogram of Oriented Gradients (HOG) features from each loaded image. HOG features are effective for capturing local object appearance and shape by describing the distribution of intensity gradients or edge directions. These features are commonly used in traditional computer vision tasks.
"""

if len(features_array) == 0:
    print("Cannot extract features: No images were loaded in the previous step.")
    hog_features = np.array([])
else:
    # Initialize HOG descriptor
    # Parameters: winSize, blockSize, blockStride, cellSize, nbins
    # winSize should be the same as the image_size defined during loading
    hog = cv2.HOGDescriptor(image_size, (16, 16), (8, 8), (8, 8), 9)

    hog_features = []
    print("Extracting HOG features...")

    for img in features_array:
        gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # HOG usually works best on grayscale images
        hist = hog.compute(gray_img) # Compute HOG features
        hog_features.append(hist.flatten()) # Flatten the features into a 1D array

    hog_features = np.array(hog_features)
    print(f"Extracted HOG features for {len(hog_features)} images. Feature dimension: {hog_features.shape[1]}")

"""#### 3. Data Preparation and Splitting

Here, the HOG features and corresponding labels are split into training and testing sets. This allows us to train the model on one portion of the data and evaluate its performance on unseen data.
"""

if len(hog_features) == 0:
    print("Cannot split data: No HOG features were extracted.")
    X_train, X_test, y_train, y_test = np.array([]), np.array([]), np.array([]), np.array([])
elif len(hog_features) < 2:
    print("Not enough samples to split into training and testing sets. Need at least 2 samples.")
    X_train, X_test, y_train, y_test = hog_features, np.array([]), labels_array, np.array([]) # Use all as training
else:
    # Split the data into training and testing sets (80% train, 20% test)
    # stratify=labels ensures that the proportion of classes is the same in both train and test sets
    X_train, X_test, y_train, y_test = train_test_split(
        hog_features, labels_array, test_size=0.2, random_state=42, stratify=labels_array
    )

    print(f"Training data shape: {X_train.shape}")
    print(f"Testing data shape: {X_test.shape}")
    print(f"Training labels count (0/NO): {np.sum(y_train == 0)}, (1/YES): {np.sum(y_train == 1)}")
    print(f"Testing labels count (0/NO): {np.sum(y_test == 0)}, (1/YES): {np.sum(y_test == 1)}")

"""#### 4. Model Training and Evaluation

This final cell trains a `RandomForestClassifier` using the training data and then evaluates its performance on the test data. A classification report and a confusion matrix are printed to provide detailed insights into the model's accuracy, precision, recall, and F1-score for each class.
"""

if len(X_train) == 0 or len(X_test) == 0:
    print("Cannot train or evaluate model: Insufficient data after splitting. Please check the image loading and feature extraction steps.")
elif len(X_train) > 0 and len(X_test) == 0:
    print("Warning: Only training data available, cannot perform testing. Model will be trained but not evaluated.")
    from sklearn.ensemble import RandomForestClassifier
    # Initialize a RandomForestClassifier model
    model = RandomForestClassifier(random_state=42, class_weight='balanced') # Updated model
    # Train the model
    model.fit(X_train, y_train)
    print("Model trained, but no test set for evaluation.")
elif len(np.unique(y_train)) < 2:
    print("Cannot train model: Training data contains only one class. Ensure both 'YES' and 'NO' categories have images.")
else:
    print("Training RandomForestClassifier model...")

    from sklearn.ensemble import RandomForestClassifier
    # Initialize a RandomForestClassifier model
    model = RandomForestClassifier(random_state=42, class_weight='balanced') # Updated model

    # Train the model
    model.fit(X_train, y_train)

    print("Model training complete.")
    print("\nEvaluating model performance...")

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, target_names=["NO", "YES"])

    print(f"Accuracy: {accuracy:.4f}")
    print("\nClassification Report:\n", report)

    # Confusion Matrix visualization
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(7, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=["NO", "YES"], yticklabels=["NO", "YES"])
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.show()

"""### Classify a New Image

This section allows you to upload a new image and use the trained `RandomForestClassifier` model to predict whether it contains a tumor ('YES') or not ('NO').
"""

from google.colab import files

# Upload a new image
print("Please upload an image for classification:")
uploaded = files.upload()

# Get the name of the uploaded file
if uploaded:
    uploaded_file_name = list(uploaded.keys())[0]
    print(f"Uploaded file: {uploaded_file_name}")
else:
    print("No file uploaded. Please try again.")
    uploaded_file_name = None

if uploaded_file_name:
    # Load the uploaded image
    new_img_path = Path(uploaded_file_name)
    new_img = cv2.imread(str(new_img_path))

    if new_img is None:
        print(f"Error: Could not load image from {new_img_path}. Please check the file path and format.")
    else:
        # Preprocess the new image (resize and convert to grayscale)
        resized_img = cv2.resize(new_img, image_size)
        gray_new_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2GRAY)

        # Extract HOG features from the new image
        new_img_hog_features = hog.compute(gray_new_img).flatten()

        # Reshape for prediction (model expects a 2D array, even for a single sample)
        new_img_hog_features = new_img_hog_features.reshape(1, -1)

        # Make a prediction
        prediction = model.predict(new_img_hog_features)
        predicted_label = "YES" if prediction[0] == 1 else "NO"

        # Display the image and prediction
        plt.figure(figsize=(6, 6))
        plt.imshow(cv2.cvtColor(new_img, cv2.COLOR_BGR2RGB)) # Display original color image
        plt.title(f"Prediction: {predicted_label}")
        plt.axis('off')
        plt.show()

        print(f"The model predicts: {predicted_label}")
else:
    print("No image was uploaded in the previous step. Skipping prediction.")

