# -*- coding: utf-8 -*-
"""SENTIMENTAL ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kyy3-TbAvCZqw9vqAJQbx-647T7NMq5
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

vocab_size = 10000
#Keep only the top 10000 most frequent words
(X_train, y_train), (X_test, y_test) = imdb.load_data(
    num_words=vocab_size
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

max_length = 200

X_train = pad_sequences(
    X_train,
    maxlen=max_length,
    padding='post'
)

X_test = pad_sequences(
    X_test,
    maxlen=max_length,
    padding='post'
)

model = Sequential([

    Embedding(
        input_dim=vocab_size,
        output_dim=64,
        input_length=max_length
    ),

    SimpleRNN(64),

    Dense(32, activation='relu'),

    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=5,
    batch_size=64
)

loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Accuracy:", accuracy)

from tensorflow.keras.datasets import imdb

word_index = imdb.get_word_index()

# Shift indices by 3 because Keras reserves 0,1,2
word_index = {k: (v + 3) for k, v in word_index.items()}

word_index["<PAD>"] = 0
word_index["<START>"] = 1
word_index["<UNK>"] = 2
word_index["<UNUSED>"] = 3

def review_to_sequence(review):

    review = review.lower().split()

    sequence = []

    for word in review:
        sequence.append(word_index.get(word, 2))  # 2 = unknown word

    return sequence

from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

max_length = 200

def predict_sentiment(review):

    sequence = review_to_sequence(review)

    padded = pad_sequences(
        [sequence],
        maxlen=max_length,
        padding='post'
    )

    prediction = model.predict(padded, verbose=0)

    score = prediction[0][0]

    print("Sentiment Score:", score)

    if score > 0.5:
        print("Positive Review ")
    else:
        print("Negative Review ")

predict_sentiment(
    "This movie was amazing and the acting was excellent"
)

predict_sentiment(
    "i dont like this movie "
)



"""IMDB DATASET"""

import pandas as pd

df = pd.read_csv("/content/IMDB Dataset.csv", encoding='latin1')

print(df.head())
print(df['sentiment'].value_counts())

df['sentiment'] = df['sentiment'].map({
    'positive': 1,
    'negative': 0
})

import re

negation_words = [
    "not good", "not bad", "not great", "don't like",
    "didn't like", "never liked", "wasn't good",
    "isn't good", "no good"
]

def clean_text(text):
    text = text.lower()

    text = re.sub(r"[^a-zA-Z\s']", " ", text)

    # convert negations into single tokens
    for phrase in negation_words:
        text = text.replace(phrase, phrase.replace(" ", "_"))

    return text

"""| Original phrase | Converted    |
| --------------- | ------------ |
| "not good"      | "not_good"   |
| "don't like"    | "don't_like" |

eg:This movie is not good at all

after transformation :This movie is not_good at all
"""



df['review'] = df['review'].apply(clean_text)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['review'],
    df['sentiment'],
    test_size=0.2,
    random_state=42
)

"""Every review is converted into a list of numbers."""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 20000
max_len = 250

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len, padding='post')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

model = Sequential([
    Embedding(vocab_size, 128, input_length=max_len),

    LSTM(128, dropout=0.3, recurrent_dropout=0.3),

    Dense(64, activation='relu'),
    Dropout(0.3),

    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train_pad,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

loss, acc = model.evaluate(X_test_pad, y_test)

print("Test Accuracy:", acc)

def predict_sentiment(review):

    review = clean_text(review)

    seq = tokenizer.texts_to_sequences([review])

    padded = pad_sequences(seq, maxlen=max_len, padding='post')

    prediction = model.predict(padded)[0][0]

    print("\nReview:", review)
    print("Score:", prediction)

    if prediction >= 0.5:
        print("Sentiment: Positive 😊")
    else:
        print("Sentiment: Negative 😞")

predict_sentiment("This movie was absolutely amazing and I loved it")

predict_sentiment("This movie was not good and I didn't like it at all")

predict_sentiment("This movie is very entertaining! ")

